.cargo/config.toml, .github/workflows/ci.yml, .github/workflows/linters.yml, .github/workflows/tests.yml, Cargo.lock, Cargo.toml, Dockerfile, xtask/Cargo.toml, xtask/perf/docker-compose.yml, xtask/perf/left.sh, xtask/perf/right.sh, xtask/src/main.rs, xtask/src/perf.rs
First version of performance measurement rig
Runs iperf3 via wireguard-go, main branch of NepTUN and the current
branch between two docker containers. The results are printed in the
job log. Probably we want to add some configurability to those scripts
but it is better to do it as we go, when we actually know what we need.
Most likely we want those improvements:
- host docker image and make automation for its update
=> LLT-5652 Performance measurements

neptun/src/device/tun_linux.rs
`new_from_tun` function contained 2 bugs:
- For interface name `.len()` would return a value that's equal to the buffer size and later treated as invalid by Telio, because it included multiple trailing nul bytes, since the name wasn't properly handled as a CString.
- Leftover code caused IOCtl with TUNSETIF to be called a second time on an already confiugred tunnel, even though it's already been called with TUNGETIF a few lines before.
So the solutions were:
- Implement proper CString handling.
- Remove the extra TUNSETIF call.
=> Fix double tunsetif and invalid cstring handling on linux

.github/workflows/linters.yml, .github/workflows/tests.yml
For some reason cargo-hack does not have a Cargo.lock file and currently one of it's dependencies requires newer version of rust that we use. Let's use latest stable for now.
=> Fix Windows CI

neptun/src/device/integration_tests/mod.rs, neptun/src/device/mod.rs
Previous implementation of api_exec was not flushing the writter after writing to it. The new one does and hance the internal buffer of BufWriter is cleared. That caused send_uapi_cmd to always return empty string. With this fix we correctly return the external buffer to which BufWritter is writing.
=> Fix DeviceHandle::send_uapi_cmd

.github/workflows/tests.yml, .gitignore, xray/Pipfile, xray/Pipfile.lock, xray/README.md, xray/analyze.py, xray/paths.py, xray/run.py, xray/src/main.rs
This MR adds a `xray-tests` github workflow that performs the tests and displays the result in text format, as well as uploading the `txt` or `png` graphs as artifacts. 
To achieve this 3 more arguments were added to xray run script:
- `--save-output` saves the analysis charts in `results` folder to be uploaded as job artifacts.
- `--ascii` output the analysis chart as text graph to be displayed in the CI job.
- `--disable-drop-privileges` flag is passed to `neptun-cli` and `boringtun-cli`, without it NepTUN is failing to start on the CI runner.
=> LLT-5878: Xray tests on CI

.github/workflows/tests.yml, Cargo.lock, neptun/Cargo.toml, neptun/src/noise/mod.rs, neptun/src/noise/session.rs, xray/Cargo.toml, xray/Pipfile, xray/analyze.py, xray/run.py, xray/src/client.rs, xray/src/event_loop.rs, xray/src/key_pair.rs, xray/src/main.rs, xray/src/pcap.rs, xray/src/utils.rs
This PR adds pcap analysis to XRay, though it's likely still not utilized as much as it could, but the infrastructure is now in place.
How it works is that the pcap file is opened in rust when the test is done, since we have the `noise::Tunn` object there that encrypted the packets, and we decrypt the packets after the fact. This requires adding some functions to noise itself, but those are feature gated so they can't be used in the wrong place. The data that is gathered from the pcaps (currently the timestamp provided by tcpdump and the sender index) are written to the CSV file, and then used in the analysis step. The previous histograms have been replaced by stacked historgrams so that the different checkin points can be seen separately.
=> Add pcap analysis to XRay

xtask/perf/left.sh, xtask/perf/right.sh
NepTUN does some performance measurements, which requires to setup real connections between peers. For that some test keys has been generated, which are not used in any real deployment. Add a note explicitly stating this fact to avoid confusion.
=> Add notice about testing keys

neptun/src/noise/mod.rs, neptun/src/noise/timers.rs
There are two cases where NepTUN might hit `ConnectionExpired` error and not proceed further in the `update_timers()` function. This has been reproduced with tcli by establishing VPN connection, suspending the process, waiting for 540seconds, resuming and observing that the state is `connecting`.
It should happen if there are no persistent-keepalives set, however in our case we have them, so the fix revolves around checking for it.
This was checked with tcli which emits keepalive package and in turn a handshake attempt afte resuming.
Both fixes were unit tested as well.
=> Make Persistent-Keepalive trigger handshakes

Cargo.lock, neptun/src/device/mod.rs
I tried to test/reproduce it in few different ways, like sending SIGUSR1 to the threads waiting in `epoll_wait`, but it doesn't result in the reported message, but it kill the whole process.
=> Downgrade the message indicating that syscall was interrupted from error to trace

neptun/src/device/mod.rs
This is a cross-porting of a hotfix that was already merged to our boringtun fork.
The underlying issue was that the client got flooded with duplicate counter error logs. This will change the log level until we can fix the underlying issue, to prevent problems for our users in the meantime.
=> LLT-6071: Reduce log level for DuplicateCounter errors

Cargo.lock, neptun/Cargo.toml, neptun/src/device/epoll.rs, neptun/src/device/integration_tests/mod.rs, neptun/src/device/kqueue.rs, neptun/src/device/mod.rs
When requested, NepTUN starts multiple threads reading from the same Tun interface. This means that all of those threads need to somehow be modified when we change the Tun from which reading should be done.
This fix stops all 'old' threads (by closing the file descriptors from which they read), and starts fresh threads opening fresh file descriptors from the specified Tun.
=> Change set_iface to take into account multiple threads running event_loop

neptun/src/sleepyinstant/mod.rs
The underlying method saturates. This comment was likely written with an old underlying implementation.
---
I was reading over the code to check for possible panics in Duration arithmetic and noticed this inconsistency in the comment. I may have misunderstood something but it seems that this just calls a method which saturates.
https://github.com/NordSecurity/NepTUN/blob/6d6e95e3459a40b669cc45e35c96a4f31fc7ead6/neptun/src/sleepyinstant/unix.rs#L44
=> Fix comment.

Cargo.lock, neptun-cli/src/main.rs, neptun/src/device/integration_tests/mod.rs, neptun/src/device/mod.rs, neptun/src/device/peer.rs
Tests have found that speeds on Android are limited because of the socket buffers, and changing these values have led to nearly double the speeds. Make socket buffer size as configurable from upstream.
=> Set custom buffer size

Cargo.lock, neptun/Cargo.toml, neptun/src/device/mod.rs, neptun/src/device/peer.rs
Remove unsafe in setting socket buffer using nix sockets instead of libc
=> Refactor setting socket buffer prints friendlier

neptun/src/device/epoll.rs, neptun/src/device/mod.rs, neptun/src/device/tun_darwin.rs, neptun/src/device/tun_linux.rs, neptun/src/noise/mod.rs, xray/src/client.rs
Add &dyn io::Write parameter to the firewall_process_outbound_callback and pass TunSocket there so that firewall can respond with reject packets.
Additionally TunSocket is stripped from write4/write6 methods which where only needed on darwin platforms. Since the only allowed write to the tun device is the proper IP packet we can read the IP version from the IP header directly in the write method. This way TunSocket can implement io::Write trait.
=> Implement io::Write for TunSocket

.github/workflows/tests.yml, xtask/perf/docker-compose.yml, xtask/perf/left.sh, xtask/perf/right.sh, xtask/src/perf.rs
Performing neptun <-> neptun tests is not the best way to benchmark performance because it hides where the bottlenecks could be (download or upload).
Instead it is better to isolate the upload and download case in its own tests with the other side as linux native wireguard.
=> Have separate download/upload tests

neptun/src/device/mod.rs
This PR attempts to optimize receiving packets in Neptun. It achieves this by reading from the socket and writing to the tunnel in separate threads and using a channel to transfer packets between them.
Thread 1 -> Reads from socket and decrypts the packet
Thread 2 -> Writes to the tunnel
It was found that packets were being dropped by the udp queue because the queue was full as it was waiting for the socket to read the packets. In the chain of read from socket -> decrypt -> write to tunnel, write to tunnel part was taking up more time compared to the previous 2 blocks hence it made sense to write to tunnel in a separate thread and introduce an intermediary buffer to hold the data.
The following is the result after experimentation on real devices relative to the current neptun performance. …
=> Breaking up Rx into 2 threads

neptun/src/device/mod.rs
Packets were being sent in between threads 1 at a time. This has overhead of waking up the thread and context switching. Instead packets can be sent together in batches reducing the wakeups and increasing throughput.
Size of 50 was selecting after experimenting with multiple batch sizes. There was not much difference observed when using a batch size of 50 vs batch size of 100.
Results from Motorola g24
Main branch - Upload - 228 Mbps
Current branch - Upload - 273 Mbps ⬆️ 24%
Main branch - Download - 176 Mbps
Current branch - Download - 269 Mbps ⬆️  52%
These results were taken from Motorola G24. On other devices, they may/may not have an impact. Pixel8 showed no change. Pixel7 showed an increase of 35% but only for the download case, upload case had no impact.
=> LLT 6218 send interthread batched packets

neptun-cli/src/main.rs, neptun/src/device/integration_tests/mod.rs, neptun/src/device/mod.rs, neptun/src/device/peer.rs
Make the channel and inter thread packets batching feature configurable. If no config is given, then it defaults to the given consts.
=> Make channel and batched pkts sizes configurable

neptun/src/device/mod.rs, neptun/src/device/peer.rs
Android team faced a problem of panics at unwrap. It is a big difficult to get to the root cause of this, hence this issue is being hotfixed.
=> panic on unwrap

Cargo.lock, neptun/Cargo.toml
Reverts NordSecurity/NepTUN#52 which should have been v2.2.1 -> v2.2.2 and not v2.2.1 -> v2.3.1
=> Revert "bump version to v2.3.1: add 32bit support"

neptun/src/noise/handshake.rs, neptun/src/noise/integration_tests/mod.rs, neptun/src/noise/mod.rs, neptun/src/noise/rate_limiter.rs, neptun/src/noise/session.rs
Use u64 instead of usize in rx and tx bytes as the value overflows just after 4GB of data and incorrectly reports state which causing the connection to go from connected -> connecting
=> Use u64 instead of usize
